### ISSUE TITLE
Add Links to Facebook, Twitter, and Instagram

### ISSUE THREAD

**Issue by braddunbar** [aikenorganics/aikenorganics.github.io#5]
@aikenorganics Can you put those links in here?

**Comment by aikenorganics** [comment]
am I suppose to do something?

**Comment by braddunbar** [comment]
Yea! What are the Twitter, Facebook, and Instagram accounts you'd like to use?

**Comment by aikenorganics** [comment]
twitter - @aikenorganics
facebook - www.facebook.com/aikenorganics
instagram - Aikenoraganics

**Comment by braddunbar** [comment]
Thanks very much! :smiley_cat:

**Comment by braddunbar** [comment]
Done and done!

![screen shot 2015-02-28 at 4 36 03 pm](https://cloud.githubusercontent.com/assets/11674/6428229/f773cf62-bf67-11e4-95bf-4d42e02ba417.png)

**Comment by aikenorganics** [comment]
Love it!
